use super::types::ProviderInfo;

pub fn all_providers() -> Vec<ProviderInfo> {
    vec![
        ProviderInfo {
            id: "ollama".into(),
            name: "Ollama (Local)".into(),
            icon: "🖥️".into(),
            default_url: "http://localhost:11434".into(),
            default_models: vec!["llama3".into()],
            needs_api_key: false,
            supports_api_key: true,
            keyring_suffix: "ollama_key".into(),
            api_path: "/api/chat".into(),
            models_endpoint: "/api/tags".into(),
            is_openai_compat: false,
            description: "100% local, private, no API key needed".into(),
            cost_tier: "free".into(),
            docs_url: "https://ollama.com".into(),
        },
        ProviderInfo {
            id: "openai".into(),
            name: "OpenAI".into(),
            icon: "🌐".into(),
            default_url: "https://api.openai.com".into(),
            default_models: vec!["gpt-4o".into(), "gpt-4o-mini".into(), "o1".into()],
            needs_api_key: true,
            supports_api_key: true,
            keyring_suffix: "openai_key".into(),
            api_path: "/v1/chat/completions".into(),
            models_endpoint: "/v1/models".into(),
            is_openai_compat: true,
            description: "Official GPT-4o, o1 models".into(),
            cost_tier: "$$$".into(),
            docs_url: "https://platform.openai.com/api-keys".into(),
        },
        ProviderInfo {
            id: "openrouter".into(),
            name: "OpenRouter".into(),
            icon: "🔀".into(),
            default_url: "https://openrouter.ai".into(),
            default_models: vec!["openai/gpt-4o".into(), "anthropic/claude-3.5-sonnet".into()],
            needs_api_key: true,
            supports_api_key: true,
            keyring_suffix: "openrouter_key".into(),
            api_path: "/api/v1/chat/completions".into(),
            models_endpoint: "/api/v1/models".into(),
            is_openai_compat: true,
            description: "200+ models, multi-provider hub".into(),
            cost_tier: "$$".into(),
            docs_url: "https://openrouter.ai/keys".into(),
        },
        ProviderInfo {
            id: "groq".into(),
            name: "Groq".into(),
            icon: "⚡".into(),
            default_url: "https://api.groq.com/openai".into(),
            default_models: vec![
                "llama-3.1-70b-versatile".into(),
                "llama-3.1-8b-instant".into(),
                "mixtral-8x7b-32768".into(),
            ],
            needs_api_key: true,
            supports_api_key: true,
            keyring_suffix: "groq_key".into(),
            api_path: "/v1/chat/completions".into(),
            models_endpoint: "/v1/models".into(),
            is_openai_compat: true,
            description: "Ultra-fast inference, LPU-powered".into(),
            cost_tier: "$".into(),
            docs_url: "https://console.groq.com/keys".into(),
        },
        ProviderInfo {
            id: "lm_studio".into(),
            name: "LM Studio".into(),
            icon: "🎬".into(),
            default_url: "http://localhost:1234".into(),
            default_models: vec![],
            needs_api_key: false,
            supports_api_key: false,
            keyring_suffix: "".into(),
            api_path: "/v1/chat/completions".into(),
            models_endpoint: "/v1/models".into(),
            is_openai_compat: true,
            description: "Local models via OpenAI-compatible API".into(),
            cost_tier: "free".into(),
            docs_url: "".into(),
        },
        ProviderInfo {
            id: "openwebui".into(),
            name: "OpenWebUI".into(),
            icon: "🌊".into(),
            default_url: "http://localhost:8080".into(),
            default_models: vec![],
            needs_api_key: false,
            supports_api_key: false,
            keyring_suffix: "".into(),
            api_path: "/v1/chat/completions".into(),
            models_endpoint: "/v1/models".into(),
            is_openai_compat: true,
            description: "Self-hosted OpenAI-compatible UI".into(),
            cost_tier: "free".into(),
            docs_url: "".into(),
        },
        ProviderInfo {
            id: "vllm".into(),
            name: "vLLM".into(),
            icon: "🚀".into(),
            default_url: "http://localhost:8000".into(),
            default_models: vec![],
            needs_api_key: false,
            supports_api_key: false,
            keyring_suffix: "".into(),
            api_path: "/v1/chat/completions".into(),
            models_endpoint: "/v1/models".into(),
            is_openai_compat: true,
            description: "High-throughput LLM serving engine".into(),
            cost_tier: "free".into(),
            docs_url: "".into(),
        },
        ProviderInfo {
            id: "together".into(),
            name: "Together AI".into(),
            icon: "🤝".into(),
            default_url: "https://api.together.xyz".into(),
            default_models: vec![
                "meta-llama/Llama-3.1-70B-Instruct-Turbo".into(),
                "mistralai/Mixtral-8x7B-Instruct-v0.1".into(),
            ],
            needs_api_key: true,
            supports_api_key: true,
            keyring_suffix: "together_key".into(),
            api_path: "/v1/chat/completions".into(),
            models_endpoint: "/v1/models".into(),
            is_openai_compat: true,
            description: "Open-source models at scale".into(),
            cost_tier: "$".into(),
            docs_url: "https://api.together.xyz/settings/api-keys".into(),
        },
        ProviderInfo {
            id: "anthropic".into(),
            name: "Anthropic (Claude)".into(),
            icon: "🧠".into(),
            default_url: "https://api.anthropic.com".into(),
            default_models: vec![
                "claude-sonnet-4-20250514".into(),
                "claude-opus-4-20250514".into(),
                "claude-3-5-haiku-20241022".into(),
            ],
            needs_api_key: true,
            supports_api_key: true,
            keyring_suffix: "anthropic_key".into(),
            api_path: "/v1/messages".into(),
            models_endpoint: "".into(),
            is_openai_compat: false,
            description: "Claude Sonnet, Opus, Haiku".into(),
            cost_tier: "$$$".into(),
            docs_url: "https://console.anthropic.com/settings/keys".into(),
        },
        ProviderInfo {
            id: "gemini".into(),
            name: "Google Gemini".into(),
            icon: "💎".into(),
            default_url: "https://generativelanguage.googleapis.com".into(),
            default_models: vec!["gemini-2.0-flash".into(), "gemini-2.5-pro".into()],
            needs_api_key: true,
            supports_api_key: true,
            keyring_suffix: "gemini_key".into(),
            api_path: "/v1beta/models/{model}:generateContent".into(),
            models_endpoint: "/v1beta/models".into(),
            is_openai_compat: false,
            description: "Gemini Flash & Pro models".into(),
            cost_tier: "$$".into(),
            docs_url: "https://aistudio.google.com/apikey".into(),
        },
        ProviderInfo {
            id: "opencode_zen".into(),
            name: "OpenCode Zen".into(),
            icon: "⌨️".into(),
            default_url: "https://opencode.ai/zen".into(),
            default_models: vec![
                "big-pickle".into(),
                "deepseek-v4-flash-free".into(),
                "mimo-v2.5-free".into(),
                "laguna-s-2.1-free".into(),
                "nemotron-3-ultra-free".into(),
                "north-mini-code-free".into(),
                "ling-3.0-flash-free".into(),
            ],
            needs_api_key: true,
            supports_api_key: true,
            keyring_suffix: "opencode_zen_key".into(),
            api_path: "/v1/chat/completions".into(),
            models_endpoint: "/v1/models".into(),
            is_openai_compat: true,
            description:
                "OpenCode Zen — modelos gratuitos y de pago optimizados para coding (pay-as-you-go)"
                    .into(),
            cost_tier: "free".into(),
            docs_url: "https://opencode.ai".into(),
        },
        ProviderInfo {
            id: "opencode_go".into(),
            name: "OpenCode Go".into(),
            icon: "🏃".into(),
            default_url: "https://opencode.ai/zen/go".into(),
            default_models: vec![
                "grok-4.5".into(),
                "kimi-k3".into(),
                "glm-5.2".into(),
                "qwen3.7-max".into(),
                "kimi-k2.7-code".into(),
                "minimax-m3".into(),
                "mimo-v2.5-pro".into(),
                "deepseek-v4-pro".into(),
                "qwen3.7-plus".into(),
                "hy3".into(),
            ],
            needs_api_key: true,
            supports_api_key: true,
            keyring_suffix: "opencode_go_key".into(),
            api_path: "/v1/chat/completions".into(),
            models_endpoint: "/v1/models".into(),
            is_openai_compat: true,
            description: "OpenCode Go — suscripción $10/mes con modelos open-source premium".into(),
            cost_tier: "$".into(),
            docs_url: "https://opencode.ai".into(),
        },
    ]
}

pub fn get_provider_info(id: &str) -> Option<ProviderInfo> {
    all_providers().into_iter().find(|p| p.id == id)
}
