/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/renderer/index.html",
        "./src/renderer/src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                card: "hsl(var(--card))",
                "card-foreground": "hsl(var(--card-foreground))",
                popover: "hsl(var(--popover))",
                "popover-foreground": "hsl(var(--popover-foreground))",
                primary: "hsl(var(--primary))",
                "primary-foreground": "hsl(var(--primary-foreground))",
                secondary: "hsl(var(--secondary))",
                "secondary-foreground": "hsl(var(--secondary-foreground))",
                muted: "hsl(var(--muted))",
                "muted-foreground": "hsl(var(--muted-foreground))",
                accent: "hsl(var(--accent))",
                "accent-foreground": "hsl(var(--accent-foreground))",
                destructive: "hsl(var(--destructive))",
                "destructive-foreground": "hsl(var(--destructive-foreground))",
                "destructive-text": "hsl(var(--destructive-text))",
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                success: "hsl(var(--success))",
                warning: "hsl(var(--warning))",
                info: "hsl(var(--info))",
                module: {
                    foreground: "hsl(var(--module-foreground))",
                    genesis: "hsl(var(--module-genesis))",
                    "genesis-text": "hsl(var(--module-genesis-text))",
                    dev: "hsl(var(--module-dev))",
                    "dev-text": "hsl(var(--module-dev-text))",
                    audit: "hsl(var(--module-audit))",
                    "audit-text": "hsl(var(--module-audit-text))",
                    studio: "hsl(var(--module-studio))",
                    "studio-text": "hsl(var(--module-studio-text))",
                    social: "hsl(var(--module-social))",
                    "social-text": "hsl(var(--module-social-text))",
                    templates: "hsl(var(--module-templates))",
                    "templates-text": "hsl(var(--module-templates-text))",
                    chat: "hsl(var(--module-chat))",
                    "chat-text": "hsl(var(--module-chat-text))",
                },
            },
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
    ],
}
