import { FormField } from '../../components/ui/DynamicForm';

export const genesisFields: FormField[] = [
    {
        id: 'objective',
        type: 'text',
        label: { es: 'Objetivo Creativo', en: 'Creative Objective' },
        placeholder: { es: 'Ej: Nueva colección de NFTs, Plugin de audio...', en: 'Ex: New NFT collection, Audio plugin...' },
        required: true,
        section: 'Core',
        icon: '🎯',
    },
    {
        id: 'technique',
        type: 'select',
        label: { es: 'Técnica de Ideación', en: 'Ideation Technique' },
        defaultValue: 'scamper',
        options: [
            { value: 'scamper', label: { es: 'SCAMPER', en: 'SCAMPER' }, description: { es: 'Sustituir, Combinar, Adaptar, Modificar, Poner en otro uso, Eliminar, Reordenar', en: 'Substitute, Combine, Adapt, Modify, Put to other use, Eliminate, Rearrange' } },
            { value: 'mashup', label: { es: 'Mash-up / Fusión', en: 'Mash-up / Fusion' }, description: { es: 'Combinar dos conceptos opuestos para crear algo nuevo', en: 'Combine two opposing concepts to create something new' } },
            { value: 'first_principles', label: { es: 'Primeros Principios', en: 'First Principles' }, description: { es: 'Descomponer en verdades fundamentales y construir desde ahí', en: 'Break down to fundamental truths and build from there' } },
            { value: 'blue_ocean', label: { es: 'Océano Azul', en: 'Blue Ocean' }, description: { es: 'Crear un nuevo espacio de mercado sin competencia', en: 'Create a new market space without competition' } },
            { value: 'worst_idea', label: { es: 'Inversión (Peor Idea)', en: 'Inversion (Worst Idea)' }, description: { es: 'Imaginar ideas terribles para invertirlas en soluciones brillantes', en: 'Imagine terrible ideas to invert into brilliant solutions' } },
            { value: 'six_thinking_hats', label: { es: 'Seis Sombreros (de Bono)', en: 'Six Thinking Hats (de Bono)' }, description: { es: 'Analizar desde 6 perspectivas: hechos, emociones, riesgos, beneficios, creatividad, proceso', en: 'Analyze from 6 perspectives: facts, emotions, risks, benefits, creativity, process' } },
            { value: 'lateral_thinking', label: { es: 'Pensamiento Lateral', en: 'Lateral Thinking' }, description: { es: 'Resolver problemas mediante enfoques indirectos y creativos', en: 'Solve problems through indirect and creative approaches' } },
        ],
        section: 'Core',
        icon: '💡',
    },
    {
        id: 'audience',
        type: 'select',
        label: { es: 'Público Objetivo', en: 'Target Audience' },
        defaultValue: 'general',
        options: [
            { value: 'general', label: { es: 'Público General', en: 'General Audience' } },
            { value: 'tech_savvy', label: { es: 'Tech Savvy / Early Adopters', en: 'Tech Savvy / Early Adopters' } },
            { value: 'investors', label: { es: 'Inversores / VCs', en: 'Investors / VCs' } },
            { value: 'creatives', label: { es: 'Artistas y Diseñadores', en: 'Artists & Designers' } },
            { value: 'gen_z', label: { es: 'Gen Z', en: 'Gen Z' } },
            { value: 'enterprise', label: { es: 'Enterprise / B2B', en: 'Enterprise / B2B' } },
            { value: 'developers', label: { es: 'Developers / Engineers', en: 'Developers / Engineers' } },
        ],
        section: 'Core',
        icon: '👥',
    },
    {
        id: 'context',
        type: 'textarea',
        label: { es: 'Contexto / Background', en: 'Context / Background' },
        placeholder: { es: 'Describe el contexto del proyecto, historia, restricciones de negocio, datos existentes...', en: 'Describe the project context, history, business constraints, existing data...' },
        helperText: { es: 'Información adicional que el modelo debe considerar', en: 'Additional information the model should consider' },
        section: 'Advanced',
        icon: '📋',
    },
    {
        id: 'restriction',
        type: 'text',
        label: { es: 'Restricción Creativa (Opcional)', en: 'Creative Restriction (Optional)' },
        placeholder: { es: 'Ej: Sin usar pantallas, Solo sonidos de naturaleza...', en: 'Ex: No screens, Only nature sounds...' },
        helperText: { es: 'Añade una restricción para forzar innovación', en: 'Add a constraint to force innovation' },
        section: 'Core',
        icon: '⚡',
    },
    {
        id: 'prompting_mode',
        type: 'select',
        label: { es: 'Modo de Prompting', en: 'Prompting Mode' },
        defaultValue: 'direct',
        options: [
            { value: 'direct', label: { es: 'Directo', en: 'Direct' }, description: { es: 'Respuesta directa sin razonamiento explícito', en: 'Direct response without explicit reasoning' } },
            { value: 'cot', label: { es: 'Chain of Thought', en: 'Chain of Thought' }, description: { es: 'Razonamiento paso a paso', en: 'Step-by-step reasoning' } },
            { value: 'zero_shot_cot', label: { es: 'Zero-shot CoT', en: 'Zero-shot CoT' }, description: { es: '"Piensa paso a paso" sin ejemplos', en: '"Think step by step" without examples' } },
            { value: 'tree_of_thought', label: { es: 'Tree of Thought', en: 'Tree of Thought' }, description: { es: 'Explora múltiples ramas de razonamiento', en: 'Explores multiple reasoning branches' } },
        ],
        section: 'Advanced',
        icon: '🧠',
    },
    {
        id: 'output_format',
        type: 'select',
        label: { es: 'Formato de Salida', en: 'Output Format' },
        defaultValue: 'markdown',
        options: [
            { value: 'markdown', label: { es: 'Markdown Estructurado', en: 'Structured Markdown' } },
            { value: 'json', label: { es: 'JSON', en: 'JSON' } },
            { value: 'table', label: { es: 'Tabla', en: 'Table' } },
            { value: 'list', label: { es: 'Lista', en: 'List' } },
            { value: 'yaml', label: { es: 'YAML', en: 'YAML' } },
            { value: 'free', label: { es: 'Libre', en: 'Free Form' } },
        ],
        section: 'Advanced',
        icon: '📄',
    },
    {
        id: 'tone',
        type: 'slider',
        label: { es: 'Tono: Técnico ↔ Creativo', en: 'Tone: Technical ↔ Creative' },
        defaultValue: 50,
        min: 0,
        max: 100,
        step: 10,
        section: 'Advanced',
        icon: '🎭',
    },
    {
        id: 'num_ideas',
        type: 'select',
        label: { es: 'Número de Ideas', en: 'Number of Ideas' },
        defaultValue: '5',
        options: [
            { value: '3', label: { es: '3 Ideas (Rápido)', en: '3 Ideas (Quick)' } },
            { value: '5', label: { es: '5 Ideas (Estándar)', en: '5 Ideas (Standard)' } },
            { value: '10', label: { es: '10 Ideas (Exhaustivo)', en: '10 Ideas (Exhaustive)' } },
            { value: '20', label: { es: '20 Ideas (Brainstorming)', en: '20 Ideas (Brainstorming)' } },
        ],
        section: 'Advanced',
        icon: '🔢',
    },
    {
        id: 'few_shot',
        type: 'textarea',
        label: { es: 'Few-Shot Examples (Opcional)', en: 'Few-Shot Examples (Optional)' },
        placeholder: { es: 'Ejemplo 1:\nEntrada: ...\nSalida: ...\n\nEjemplo 2:\nEntrada: ...\nSalida: ...', en: 'Example 1:\nInput: ...\nOutput: ...\n\nExample 2:\nInput: ...\nOutput: ...' },
        helperText: { es: '1-3 ejemplos de entrada/salida para guiar al modelo', en: '1-3 input/output examples to guide the model' },
        section: 'Advanced',
        icon: '📝',
    },
    {
        id: 'chain_mode',
        type: 'toggle',
        label: { es: 'Modo Cadena (Ideación → Evaluación → Plan)', en: 'Chain Mode (Ideation → Evaluation → Plan)' },
        defaultValue: false,
        section: 'Advanced',
        icon: '🔗',
    },
];

export const devFields: FormField[] = [
    {
        id: 'projectType',
        type: 'select',
        label: { es: 'Tipo de Proyecto', en: 'Project Type' },
        defaultValue: 'web_app',
        options: [
            { value: 'web_app', label: { es: 'Web App (SPA / SSR)', en: 'Web App (SPA / SSR)' } },
            { value: 'desktop_app', label: { es: 'Desktop App (Cross-Platform)', en: 'Desktop App (Cross-Platform)' } },
            { value: 'mobile_app', label: { es: 'Mobile App (Nativa / Híbrida)', en: 'Mobile App (Native / Hybrid)' } },
            { value: 'devops', label: { es: 'DevOps & Infraestructura', en: 'DevOps & Infrastructure' } },
            { value: 'backend_api', label: { es: 'Backend / API RESTful', en: 'Backend / API RESTful' } },
            { value: 'multimedia', label: { es: 'Multimedia & Creative Coding', en: 'Multimedia & Creative Coding' } },
            { value: 'data_science', label: { es: 'Data Science / MLOps', en: 'Data Science / MLOps' } },
            { value: 'cli_tool', label: { es: 'CLI Tool / Package', en: 'CLI Tool / Package' } },
            { value: 'game', label: { es: 'Game / Interactive App', en: 'Game / Interactive App' } },
        ],
        section: 'Core',
        icon: '📦',
    },
    {
        id: 'arch',
        type: 'select',
        label: { es: 'Arquitectura', en: 'Architecture' },
        defaultValue: 'clean_architecture',
        options: [
            { value: 'clean_architecture', label: { es: 'Clean Architecture', en: 'Clean Architecture' } },
            { value: 'vertical_slice', label: { es: 'Vertical Slice', en: 'Vertical Slice' } },
            { value: 'micro_frontends', label: { es: 'Micro-Frontends', en: 'Micro-Frontends' } },
            { value: 'ddd', label: { es: 'Domain-Driven Design (DDD)', en: 'Domain-Driven Design (DDD)' } },
            { value: 'cqrs', label: { es: 'CQRS + Event Sourcing', en: 'CQRS + Event Sourcing' } },
            { value: 'microservices', label: { es: 'Microservices', en: 'Microservices' } },
            { value: 'modular_monolith', label: { es: 'Modular Monolith', en: 'Modular Monolith' } },
            { value: 'serverless', label: { es: 'Serverless / Event-Driven', en: 'Serverless / Event-Driven' } },
            { value: 'mvc', label: { es: 'MVC / MVVM', en: 'MVC / MVVM' } },
        ],
        section: 'Core',
        icon: '🏗️',
    },
    {
        id: 'focus',
        type: 'select',
        label: { es: 'Enfoque Estratégico', en: 'Strategic Focus' },
        defaultValue: 'balanced',
        options: [
            { value: 'balanced', label: { es: '⚖️ Balanceado (Calidad/Velocidad)', en: '⚖️ Balanced (Quality/Speed)' } },
            { value: 'performance', label: { es: '🚀 Rendimiento Extremo', en: '🚀 Ultra-Performance' } },
            { value: 'security', label: { es: '🛡️ Seguridad (Zero Trust)', en: '🛡️ Hardcore Security (Zero Trust)' } },
            { value: 'scalability', label: { es: '📈 Escalabilidad Masiva', en: '📈 Massive Scalability' } },
            { value: 'maintainability', label: { es: '🧹 Clean Code & Mantenibilidad', en: '🧹 Clean Code & Maintainability' } },
            { value: 'accessibility', label: { es: '♿ Accesibilidad (WCAG)', en: '♿ Accessibility (WCAG)' } },
        ],
        section: 'Core',
        icon: '🎯',
    },
    {
        id: 'techStack',
        type: 'text',
        label: { es: 'Stack Tecnológico', en: 'Tech Stack' },
        placeholder: { es: 'Ej: Tauri, React, Rust, PostgreSQL...', en: 'Ex: Tauri, React, Rust, PostgreSQL...' },
        section: 'Core',
        icon: '🛠️',
    },
    {
        id: 'requirements',
        type: 'textarea',
        label: { es: 'Requisitos Funcionales', en: 'Functional Requirements' },
        placeholder: { es: '- Describe las funcionalidades clave...', en: '- Describe key functionalities...' },
        section: 'Core',
        icon: '📋',
    },
    {
        id: 'database',
        type: 'select',
        label: { es: 'Base de Datos', en: 'Database' },
        defaultValue: 'none',
        options: [
            { value: 'none', label: { es: 'Sin base de datos', en: 'No database' } },
            { value: 'postgresql', label: { es: 'PostgreSQL', en: 'PostgreSQL' } },
            { value: 'mysql', label: { es: 'MySQL / MariaDB', en: 'MySQL / MariaDB' } },
            { value: 'sqlite', label: { es: 'SQLite', en: 'SQLite' } },
            { value: 'mongodb', label: { es: 'MongoDB', en: 'MongoDB' } },
            { value: 'redis', label: { es: 'Redis', en: 'Redis' } },
            { value: 'supabase', label: { es: 'Supabase', en: 'Supabase' } },
        ],
        section: 'Technical',
        icon: '🗄️',
    },
    {
        id: 'apiType',
        type: 'select',
        label: { es: 'Tipo de API', en: 'API Type' },
        defaultValue: 'rest',
        options: [
            { value: 'rest', label: { es: 'REST', en: 'REST' } },
            { value: 'graphql', label: { es: 'GraphQL', en: 'GraphQL' } },
            { value: 'grpc', label: { es: 'gRPC', en: 'gRPC' } },
            { value: 'trpc', label: { es: 'tRPC', en: 'tRPC' } },
            { value: 'websocket', label: { es: 'WebSocket', en: 'WebSocket' } },
            { value: 'none', label: { es: 'Sin API', en: 'No API' } },
        ],
        section: 'Technical',
        icon: '🔌',
    },
    {
        id: 'deployment',
        type: 'select',
        label: { es: 'Target de Deployment', en: 'Deployment Target' },
        defaultValue: 'local',
        options: [
            { value: 'local', label: { es: 'Local / Development', en: 'Local / Development' } },
            { value: 'docker', label: { es: 'Docker', en: 'Docker' } },
            { value: 'kubernetes', label: { es: 'Kubernetes', en: 'Kubernetes' } },
            { value: 'serverless_aws', label: { es: 'Serverless (AWS Lambda)', en: 'Serverless (AWS Lambda)' } },
            { value: 'serverless_gcp', label: { es: 'Serverless (GCP Cloud Functions)', en: 'Serverless (GCP Cloud Functions)' } },
            { value: 'vps', label: { es: 'VPS / Bare Metal', en: 'VPS / Bare Metal' } },
            { value: 'vercel', label: { es: 'Vercel / Netlify', en: 'Vercel / Netlify' } },
        ],
        section: 'Technical',
        icon: '🚀',
    },
    {
        id: 'security',
        type: 'toggle',
        label: { es: 'Incluir Seguridad (SAST, OWASP, Threat Model)', en: 'Include Security (SAST, OWASP, Threat Model)' },
        defaultValue: false,
        section: 'Quality',
        icon: '🛡️',
    },
    {
        id: 'testingStrategy',
        type: 'select',
        label: { es: 'Estrategia de Testing', en: 'Testing Strategy' },
        defaultValue: 'unit',
        options: [
            { value: 'none', label: { es: 'Sin tests', en: 'No tests' } },
            { value: 'unit', label: { es: 'Unit Tests only', en: 'Unit Tests only' } },
            { value: 'unit_integration', label: { es: 'Unit + Integration', en: 'Unit + Integration' } },
            { value: 'tdd', label: { es: 'Full TDD', en: 'Full TDD' } },
            { value: 'bdd', label: { es: 'BDD (Cucumber/Gherkin)', en: 'BDD (Cucumber/Gherkin)' } },
            { value: 'property', label: { es: 'Property-based Testing', en: 'Property-based Testing' } },
        ],
        section: 'Quality',
        icon: '🧪',
    },
    {
        id: 'qualityGates',
        type: 'multiselect',
        label: { es: 'Quality Gates', en: 'Quality Gates' },
        defaultValue: [],
        options: [
            { value: 'typescript_strict', label: { es: 'TypeScript Strict', en: 'TypeScript Strict' } },
            { value: 'eslint', label: { es: 'ESLint', en: 'ESLint' } },
            { value: 'prettier', label: { es: 'Prettier', en: 'Prettier' } },
            { value: 'husky', label: { es: 'Husky (pre-commit hooks)', en: 'Husky (pre-commit hooks)' } },
            { value: 'semantic_commits', label: { es: 'Semantic Commits', en: 'Semantic Commits' } },
            { value: 'conventional_commits', label: { es: 'Conventional Commits', en: 'Conventional Commits' } },
            { value: 'sbom', label: { es: 'SBOM Generation', en: 'SBOM Generation' } },
        ],
        section: 'Quality',
        icon: '✅',
    },
    {
        id: 'style',
        type: 'select',
        label: { es: 'Estilo UI/UX', en: 'UI/UX Style' },
        defaultValue: 'native',
        options: [
            { value: 'native', label: { es: 'Sistema Nativo', en: 'Native System Look' } },
            { value: 'material', label: { es: 'Material Design 3', en: 'Material Design 3' } },
            { value: 'minimalist', label: { es: 'Minimalismo Suizo', en: 'Swiss Minimalism' } },
            { value: 'glass', label: { es: 'Glassmorphism', en: 'Glassmorphism' } },
            { value: 'cli', label: { es: 'Terminal / CLI', en: 'Terminal / CLI' } },
        ],
        section: 'Technical',
        icon: '🎨',
    },
    {
        id: 'level',
        type: 'select',
        label: { es: 'Nivel de Entrega', en: 'Delivery Level' },
        defaultValue: 'prod',
        options: [
            { value: 'scaffold', label: { es: 'Estructura Base / Scaffold', en: 'Base Structure / Scaffold' } },
            { value: 'mvp', label: { es: 'MVP Funcional', en: 'Functional MVP' } },
            { value: 'prod', label: { es: 'Production-Ready', en: 'Production-Ready' } },
        ],
        section: 'Core',
        icon: '📦',
    },
    {
        id: 'outputGranularity',
        type: 'select',
        label: { es: 'Granularidad de Salida', en: 'Output Granularity' },
        defaultValue: 'full',
        options: [
            { value: 'full', label: { es: 'Full Codebase', en: 'Full Codebase' } },
            { value: 'core', label: { es: 'Core Module Only', en: 'Core Module Only' } },
            { value: 'architecture', label: { es: 'Architecture Diagram + Key Files', en: 'Architecture Diagram + Key Files' } },
            { value: 'scaffold', label: { es: 'Scaffold Only', en: 'Scaffold Only' } },
        ],
        section: 'Technical',
        icon: '🔍',
    },
    {
        id: 'dependencies',
        type: 'textarea',
        label: { es: 'Dependencias (usar/evitar)', en: 'Dependencies (use/avoid)' },
        placeholder: { es: 'Usar: tailwind, zod\nEvitar: jquery, moment.js', en: 'Use: tailwind, zod\nAvoid: jquery, moment.js' },
        section: 'Technical',
        icon: '📦',
    },
];

export const auditFields: FormField[] = [
    {
        id: 'inputMode',
        type: 'radio-group',
        label: { es: 'Modo de Entrada', en: 'Input Mode' },
        defaultValue: 'url',
        options: [
            { value: 'url', label: { es: 'URL de Repo', en: 'Repo URL' }, description: { es: 'Analiza un repositorio de GitHub/GitLab', en: 'Analyze a GitHub/GitLab repository' } },
            { value: 'paste', label: { es: 'Pegar Código', en: 'Paste Code' }, description: { es: 'Pega código directamente para auditar', en: 'Paste code directly to audit' } },
        ],
        section: 'Core',
        icon: '📥',
    },
    {
        id: 'repoUrl',
        type: 'text',
        label: { es: 'URL del Repositorio', en: 'Repository URL' },
        placeholder: { es: 'https://github.com/...', en: 'https://github.com/...' },
        visible: (v: Record<string, any>) => v.inputMode === 'url',
        section: 'Core',
        icon: '🔗',
    },
    {
        id: 'codeInput',
        type: 'textarea',
        label: { es: 'Código a Auditar', en: 'Code to Audit' },
        placeholder: { es: 'Pega tu código aquí...', en: 'Paste your code here...' },
        visible: (v: Record<string, any>) => v.inputMode === 'paste',
        section: 'Core',
        icon: '💻',
    },
    {
        id: 'language',
        type: 'select',
        label: { es: 'Lenguaje / Framework', en: 'Language / Framework' },
        defaultValue: 'auto',
        options: [
            { value: 'auto', label: { es: 'Auto-detectar', en: 'Auto-detect' } },
            { value: 'typescript', label: { es: 'TypeScript / JavaScript', en: 'TypeScript / JavaScript' } },
            { value: 'python', label: { es: 'Python', en: 'Python' } },
            { value: 'rust', label: { es: 'Rust', en: 'Rust' } },
            { value: 'go', label: { es: 'Go', en: 'Go' } },
            { value: 'java', label: { es: 'Java / Kotlin', en: 'Java / Kotlin' } },
            { value: 'csharp', label: { es: 'C# / .NET', en: 'C# / .NET' } },
            { value: 'php', label: { es: 'PHP', en: 'PHP' } },
            { value: 'ruby', label: { es: 'Ruby', en: 'Ruby' } },
        ],
        section: 'Core',
        icon: '🔤',
    },
    {
        id: 'artifactType',
        type: 'select',
        label: { es: 'Tipo de Artefacto', en: 'Artifact Type' },
        defaultValue: 'library',
        options: [
            { value: 'library', label: { es: '📦 Librería / SDK / Framework', en: '📦 Library / SDK / Framework' } },
            { value: 'cli', label: { es: '💻 CLI Script / Herramienta Terminal', en: '💻 CLI Script / Terminal Tool' } },
            { value: 'gui', label: { es: '🖥️ Aplicación GUI (Web/Desktop)', en: '🖥️ GUI Application (Web/Desktop)' } },
            { value: 'api', label: { es: '🔌 API / Microservicio', en: '🔌 API / Microservice' } },
            { value: 'mobile', label: { es: '📱 Aplicación Móvil', en: '📱 Mobile Application' } },
            { value: 'infra', label: { es: '🏗️ Infraestructura (Terraform/K8s)', en: '🏗️ Infrastructure (Terraform/K8s)' } },
        ],
        section: 'Core',
        icon: '📦',
    },
    {
        id: 'scanTypes',
        type: 'multiselect',
        label: { es: 'Tipos de Scan', en: 'Scan Types' },
        defaultValue: ['owasp', 'input_validation', 'auth'],
        options: [
            { value: 'sast', label: { es: 'SAST (Análisis Estático)', en: 'SAST (Static Analysis)' } },
            { value: 'sca', label: { es: 'SCA (Dependencias)', en: 'SCA (Dependencies)' } },
            { value: 'secrets', label: { es: 'Secrets Detection', en: 'Secrets Detection' } },
            { value: 'owasp', label: { es: 'OWASP Top 10', en: 'OWASP Top 10' } },
            { value: 'input_validation', label: { es: 'Input Validation', en: 'Input Validation' } },
            { value: 'auth', label: { es: 'Auth / Session Security', en: 'Auth / Session Security' } },
            { value: 'error_handling', label: { es: 'Error Handling', en: 'Error Handling' } },
        ],
        section: 'Scan',
        icon: '🔍',
    },
    {
        id: 'severity',
        type: 'select',
        label: { es: 'Umbral de Severidad', en: 'Severity Threshold' },
        defaultValue: 'critical_high',
        options: [
            { value: 'critical', label: { es: 'Solo Críticos', en: 'Critical Only' } },
            { value: 'critical_high', label: { es: 'Críticos + Altos', en: 'Critical + High' } },
            { value: 'all', label: { es: 'Todos', en: 'All Severities' } },
        ],
        section: 'Scan',
        icon: '⚠️',
    },
    {
        id: 'compliance',
        type: 'select',
        label: { es: 'Framework de Compliance', en: 'Compliance Framework' },
        defaultValue: 'none',
        options: [
            { value: 'none', label: { es: 'Ninguno', en: 'None' } },
            { value: 'soc2', label: { es: 'SOC 2', en: 'SOC 2' } },
            { value: 'iso27001', label: { es: 'ISO 27001', en: 'ISO 27001' } },
            { value: 'pci_dss', label: { es: 'PCI DSS', en: 'PCI DSS' } },
            { value: 'hipaa', label: { es: 'HIPAA', en: 'HIPAA' } },
            { value: 'gdpr', label: { es: 'GDPR', en: 'GDPR' } },
        ],
        section: 'Scan',
        icon: '📜',
    },
    {
        id: 'includeFixes',
        type: 'toggle',
        label: { es: 'Incluir Sugerencias de Código Corregido', en: 'Include Fixed Code Suggestions' },
        defaultValue: true,
        section: 'Report',
        icon: '🔧',
    },
    {
        id: 'falsePositiveFilter',
        type: 'toggle',
        label: { es: 'Marcar Posibles Falsos Positivos', en: 'Flag Possible False Positives' },
        defaultValue: true,
        section: 'Report',
        icon: '🎯',
    },
    {
        id: 'reportFormat',
        type: 'select',
        label: { es: 'Formato del Reporte', en: 'Report Format' },
        defaultValue: 'full',
        options: [
            { value: 'executive', label: { es: 'Executive Summary', en: 'Executive Summary' } },
            { value: 'technical', label: { es: 'Technical Deep Dive', en: 'Technical Deep Dive' } },
            { value: 'full', label: { es: 'Full Report (Both)', en: 'Full Report (Both)' } },
            { value: 'checklist', label: { es: 'Checklist', en: 'Checklist' } },
        ],
        section: 'Report',
        icon: '📊',
    },
];

export const studioFields: FormField[] = [
    {
        id: 'topic',
        type: 'text',
        label: { es: 'Tema o Documento Base', en: 'Topic or Base Document' },
        placeholder: { es: 'Ej: Microservicios, Historia del Arte...', en: 'Ex: Microservices, Art History...' },
        required: true,
        section: 'Core',
        icon: '📝',
    },
    {
        id: 'profile',
        type: 'select',
        label: { es: 'Perfil / Audiencia', en: 'Profile / Audience' },
        defaultValue: 'expert',
        options: [
            { value: 'expert', label: { es: '🧠 Experto a Experto (SME)', en: '🧠 Expert to Expert (SME)' } },
            { value: 'student', label: { es: '🎓 Estudiante (Rigor Académico)', en: '🎓 Student (Academic Rigor)' } },
            { value: 'creative', label: { es: '🎨 Creativo (Enfoque Conceptual)', en: '🎨 Creative (Conceptual)' } },
            { value: 'executive', label: { es: '💼 Ejecutivo / C-Level', en: '💼 Executive / C-Level' } },
            { value: 'beginner', label: { es: '🌱 Principiante', en: '🌱 Beginner' } },
            { value: 'developer', label: { es: '💻 Developer / Engineer', en: '💻 Developer / Engineer' } },
        ],
        section: 'Core',
        icon: '👤',
    },
    {
        id: 'funnelStage',
        type: 'select',
        label: { es: 'Etapa del Funnel', en: 'Funnel Stage' },
        defaultValue: 'awareness',
        options: [
            { value: 'awareness', label: { es: 'TOFU (Awareness)', en: 'TOFU (Awareness)' } },
            { value: 'consideration', label: { es: 'MOFU (Consideration)', en: 'MOFU (Consideration)' } },
            { value: 'decision', label: { es: 'BOFU (Decision)', en: 'BOFU (Decision)' } },
            { value: 'retention', label: { es: 'Retention', en: 'Retention' } },
        ],
        section: 'Strategy',
        icon: '📊',
    },
    {
        id: 'contentPillar',
        type: 'text',
        label: { es: 'Pilar de Contenido', en: 'Content Pillar' },
        placeholder: { es: 'Ej: Educación, Producto, Thought Leadership...', en: 'Ex: Education, Product, Thought Leadership...' },
        helperText: { es: 'El pilar temático al que pertenece este contenido', en: 'The thematic pillar this content belongs to' },
        section: 'Strategy',
        icon: '🏛️',
    },
    {
        id: 'frame',
        type: 'select',
        label: { es: 'Marco Mental', en: 'Mental Framework' },
        defaultValue: 'first_principles',
        options: [
            { value: 'first_principles', label: { es: 'Principios Primeros', en: 'First Principles' } },
            { value: 'feynman', label: { es: 'Técnica Feynman', en: 'Feynman Technique' } },
            { value: 'critical_thinking', label: { es: 'Pensamiento Crítico', en: 'Critical Thinking' } },
            { value: 'pareto', label: { es: 'Análisis 80/20', en: '80/20 Analysis' } },
            { value: 'analogy', label: { es: 'Pensamiento Analógico', en: 'Analogical Thinking' } },
            { value: 'systems_thinking', label: { es: 'Pensamiento Sistémico', en: 'Systems Thinking' } },
        ],
        section: 'Core',
        icon: '🧠',
    },
    {
        id: 'format',
        type: 'select',
        label: { es: 'Formato de Salida', en: 'Output Format' },
        defaultValue: 'report',
        options: [
            { value: 'report', label: { es: '📄 Informe Técnico / Paper', en: '📄 Technical Report / Paper' } },
            { value: 'blog', label: { es: '📝 Blog Post', en: '📝 Blog Post' } },
            { value: 'newsletter', label: { es: '📧 Newsletter', en: '📧 Newsletter' } },
            { value: 'case_study', label: { es: '📋 Caso de Éxito', en: '📋 Case Study' } },
            { value: 'white_paper', label: { es: '📘 White Paper / Libro Blanco', en: '📘 White Paper' } },
            { value: 'tutorial', label: { es: '🔧 Tutorial Paso a Paso', en: '🔧 Step-by-Step Tutorial' } },
            { value: 'thought_leadership', label: { es: '💡 Liderazgo de Opinión', en: '💡 Thought Leadership' } },
            { value: 'video_script', label: { es: '📹 Guion de Video', en: '📹 Video Script' } },
            { value: 'press_release', label: { es: '📰 Comunicado de Prensa', en: '📰 Press Release' } },
            { value: 'email_sequence', label: { es: '📬 Secuencia de Emails', en: '📬 Email Sequence' } },
            { value: 'social_post', label: { es: '🔤 Post para Redes Sociales', en: '🔤 Social Media Post' } },
            { value: 'podcast', label: { es: '🎙️ Guion Podcast (Debate)', en: '🎙️ Podcast Script (Debate)' } },
            { value: 'slides', label: { es: '🖼️ Presentación Académica', en: '🖼️ Academic Presentation' } },
            { value: 'infographic', label: { es: '📊 Estructura Visual', en: '📊 Visual Structure' } },
            { value: 'framework', label: { es: '🧩 Metodología / Syllabus', en: '🧩 Methodology / Syllabus' } },
        ],
        section: 'Core',
        icon: '📄',
    },
    {
        id: 'wordCount',
        type: 'select',
        label: { es: 'Extensión', en: 'Word Count' },
        defaultValue: 'medium',
        options: [
            { value: 'short', label: { es: 'Corto (500-800 palabras)', en: 'Short (500-800 words)' } },
            { value: 'medium', label: { es: 'Medio (1000-2000 palabras)', en: 'Medium (1000-2000 words)' } },
            { value: 'long', label: { es: 'Largo (2000-5000 palabras)', en: 'Long (2000-5000 words)' } },
            { value: 'custom', label: { es: 'Personalizado', en: 'Custom' } },
        ],
        section: 'Strategy',
        icon: '📏',
    },
    {
        id: 'seoKeywords',
        type: 'tags',
        label: { es: 'SEO Keywords', en: 'SEO Keywords' },
        placeholder: { es: 'Escribe y presiona Enter...', en: 'Type and press Enter...' },
        helperText: { es: 'Keywords objetivo que deben incluirse', en: 'Target keywords that should be included' },
        section: 'Strategy',
        icon: '🔍',
    },
    {
        id: 'ctaGoal',
        type: 'select',
        label: { es: 'Objetivo CTA', en: 'CTA Goal' },
        defaultValue: 'none',
        options: [
            { value: 'none', label: { es: 'Sin CTA', en: 'No CTA' } },
            { value: 'newsletter', label: { es: 'Newsletter Signup', en: 'Newsletter Signup' } },
            { value: 'demo', label: { es: 'Product Demo', en: 'Product Demo' } },
            { value: 'download', label: { es: 'Download / Lead Magnet', en: 'Download / Lead Magnet' } },
            { value: 'share', label: { es: 'Share / Repost', en: 'Share / Repost' } },
            { value: 'purchase', label: { es: 'Purchase / Subscribe', en: 'Purchase / Subscribe' } },
        ],
        section: 'Strategy',
        icon: '🎯',
    },
    {
        id: 'tone',
        type: 'select',
        label: { es: 'Tono', en: 'Tone' },
        defaultValue: 'professional',
        options: [
            { value: 'academic', label: { es: 'Académico', en: 'Academic' } },
            { value: 'conversational', label: { es: 'Conversacional', en: 'Conversational' } },
            { value: 'authoritative', label: { es: 'Autoritativo', en: 'Authoritative' } },
            { value: 'storytelling', label: { es: 'Storytelling', en: 'Storytelling' } },
            { value: 'technical', label: { es: 'Técnico', en: 'Technical' } },
            { value: 'inspirational', label: { es: 'Inspiracional', en: 'Inspirational' } },
        ],
        section: 'Strategy',
        icon: '🎭',
    },
    {
        id: 'includeData',
        type: 'toggle',
        label: { es: 'Incluir Estadísticas y Datos de Soporte', en: 'Include Statistics and Supporting Data' },
        defaultValue: true,
        section: 'Content',
        icon: '📈',
    },
    {
        id: 'repurposing',
        type: 'multiselect',
        label: { es: 'Versiones para Repurposing', en: 'Repurposing Versions' },
        defaultValue: [],
        options: [
            { value: 'linkedin', label: { es: 'LinkedIn Post', en: 'LinkedIn Post' } },
            { value: 'twitter_thread', label: { es: 'Twitter Thread', en: 'Twitter Thread' } },
            { value: 'email', label: { es: 'Email Newsletter', en: 'Email Newsletter' } },
            { value: 'instagram_carousel', label: { es: 'Instagram Carousel', en: 'Instagram Carousel' } },
            { value: 'tiktok_script', label: { es: 'TikTok/Reel Script', en: 'TikTok/Reel Script' } },
        ],
        section: 'Distribution',
        icon: '🔄',
    },
    {
        id: 'structuredOutput',
        type: 'toggle',
        label: { es: 'Output JSON Estructurado (para CMS)', en: 'Structured JSON Output (for CMS)' },
        defaultValue: false,
        section: 'Content',
        icon: '🔧',
    },
];

export const socialFields: FormField[] = [
    {
        id: 'platform',
        type: 'select',
        label: { es: 'Plataforma', en: 'Platform' },
        defaultValue: 'linkedin',
        options: [
            { value: 'linkedin', label: { es: 'LinkedIn', en: 'LinkedIn' } },
            { value: 'twitter', label: { es: 'X / Twitter', en: 'X / Twitter' } },
            { value: 'instagram', label: { es: 'Instagram', en: 'Instagram' } },
            { value: 'tiktok', label: { es: 'TikTok', en: 'TikTok' } },
            { value: 'youtube', label: { es: 'YouTube', en: 'YouTube' } },
            { value: 'facebook', label: { es: 'Facebook', en: 'Facebook' } },
        ],
        section: 'Core',
        icon: '📱',
    },
    {
        id: 'topic',
        type: 'text',
        label: { es: 'Tema / Producto', en: 'Topic / Product' },
        placeholder: { es: 'Ej: Nuevo Single, App Finanzas...', en: 'Ex: New Single, Finance App...' },
        required: true,
        section: 'Core',
        icon: '🎯',
    },
    {
        id: 'audience',
        type: 'text',
        label: { es: 'Audiencia', en: 'Audience' },
        placeholder: { es: 'Ej: Gen-Z, Developers...', en: 'Ex: Gen-Z, Developers...' },
        section: 'Core',
        icon: '👥',
    },
    {
        id: 'hookType',
        type: 'select',
        label: { es: 'Tipo de Hook', en: 'Hook Type' },
        defaultValue: 'curiosity',
        options: [
            { value: 'curiosity', label: { es: 'Curiosity Gap', en: 'Curiosity Gap' }, description: { es: 'Deja un vacío de información que el lector debe llenar', en: 'Leave an information void the reader must fill' } },
            { value: 'story', label: { es: 'Story Hook', en: 'Story Hook' }, description: { es: 'Narrativa que crea inversión emocional', en: 'Narrative that creates emotional investment' } },
            { value: 'value', label: { es: 'Value-First', en: 'Value-First' }, description: { es: 'Promete utilidad inmediata', en: 'Promises immediate utility' } },
            { value: 'contrarian', label: { es: 'Contrarian', en: 'Contrarian' }, description: { es: 'Desafía suposiciones populares', en: 'Challenges popular assumptions' } },
            { value: 'emotional', label: { es: 'Emotional', en: 'Emotional' }, description: { es: 'Conecta con una emoción fuerte', en: 'Connects to a strong feeling' } },
            { value: 'hot_take', label: { es: 'Hot Take', en: 'Hot Take' }, description: { es: 'Opinión fuerte y directa', en: 'Strong, direct opinion' } },
        ],
        section: 'Psychology',
        icon: '🪝',
    },
    {
        id: 'engagementGoal',
        type: 'select',
        label: { es: 'Objetivo de Engagement', en: 'Engagement Goal' },
        defaultValue: 'comments',
        options: [
            { value: 'comments', label: { es: 'Comentarios', en: 'Comments' } },
            { value: 'saves', label: { es: 'Guardados', en: 'Saves' } },
            { value: 'shares', label: { es: 'Compartidos', en: 'Shares' } },
            { value: 'follows', label: { es: 'Seguidores', en: 'Follows' } },
            { value: 'clicks', label: { es: 'Link Clicks', en: 'Link Clicks' } },
            { value: 'dms', label: { es: 'DMs / Mensajes', en: 'DMs / Messages' } },
        ],
        section: 'Psychology',
        icon: '🎯',
    },
    {
        id: 'psychTrigger',
        type: 'select',
        label: { es: 'Trigger Psicológico', en: 'Psychological Trigger' },
        defaultValue: 'social_proof',
        options: [
            { value: 'social_proof', label: { es: 'Social Proof', en: 'Social Proof' } },
            { value: 'scarcity', label: { es: 'Scarcity / FOMO', en: 'Scarcity / FOMO' } },
            { value: 'authority', label: { es: 'Authority', en: 'Authority' } },
            { value: 'reciprocity', label: { es: 'Reciprocity', en: 'Reciprocity' } },
            { value: 'identity', label: { es: 'Identity / In-Group', en: 'Identity / In-Group' } },
            { value: 'loss_aversion', label: { es: 'Loss Aversion', en: 'Loss Aversion' } },
        ],
        section: 'Psychology',
        icon: '🧠',
    },
    {
        id: 'framework',
        type: 'select',
        label: { es: 'Framework Persuasivo', en: 'Persuasive Framework' },
        defaultValue: 'storytelling',
        options: [
            { value: 'storytelling', label: { es: 'Storytelling', en: 'Storytelling' } },
            { value: 'pas', label: { es: 'PAS (Problema - Agitación)', en: 'PAS (Problem - Agitation)' } },
            { value: 'aida', label: { es: 'AIDA', en: 'AIDA' } },
            { value: 'bridge', label: { es: 'Bridge (Antes-Después)', en: 'Bridge (Before-After)' } },
            { value: 'hype', label: { es: 'Hype / Drop (Escasez)', en: 'Hype / Drop (Scarcity)' } },
        ],
        section: 'Core',
        icon: '🔥',
    },
    {
        id: 'tone',
        type: 'select',
        label: { es: 'Mood / Tono', en: 'Mood / Tone' },
        defaultValue: 'professional',
        options: [
            { value: 'professional', label: { es: 'Profesional / Líder', en: 'Professional / Leader' } },
            { value: 'casual', label: { es: 'Casual / Cercano', en: 'Casual / Approachable' } },
            { value: 'witty', label: { es: 'Ingenioso / Humor', en: 'Witty / Humorous' } },
            { value: 'vulnerable', label: { es: 'Vulnerable / Auténtico', en: 'Vulnerable / Authentic' } },
            { value: 'contrarian', label: { es: 'Contrarian / Disruptivo', en: 'Contrarian / Disruptive' } },
            { value: 'educational', label: { es: 'Educativo', en: 'Educational' } },
            { value: 'artistic', label: { es: 'Artístico / Abstracto', en: 'Artistic / Abstract' } },
        ],
        section: 'Core',
        icon: '🎭',
    },
    {
        id: 'contentLength',
        type: 'select',
        label: { es: 'Longitud del Contenido', en: 'Content Length' },
        defaultValue: 'medium',
        options: [
            { value: 'micro', label: { es: 'Micro (<100 chars)', en: 'Micro (<100 chars)' } },
            { value: 'short', label: { es: 'Corto (100-500)', en: 'Short (100-500)' } },
            { value: 'medium', label: { es: 'Medio (500-1500)', en: 'Medium (500-1500)' } },
            { value: 'long', label: { es: 'Largo (1500+)', en: 'Long (1500+)' } },
        ],
        section: 'Format',
        icon: '📏',
    },
    {
        id: 'includeHashtags',
        type: 'toggle',
        label: { es: 'Incluir Hashtags', en: 'Include Hashtags' },
        defaultValue: true,
        section: 'Format',
        icon: '#️⃣',
    },
    {
        id: 'hashtagCount',
        type: 'select',
        label: { es: 'Cantidad de Hashtags', en: 'Hashtag Count' },
        defaultValue: '5',
        visible: (v: Record<string, any>) => v.includeHashtags,
        options: [
            { value: '3', label: { es: '3 Hashtags', en: '3 Hashtags' } },
            { value: '5', label: { es: '5 Hashtags', en: '5 Hashtags' } },
            { value: '10', label: { es: '10 Hashtags', en: '10 Hashtags' } },
            { value: '15', label: { es: '15 Hashtags', en: '15 Hashtags' } },
            { value: '20', label: { es: '20 Hashtags', en: '20 Hashtags' } },
        ],
        section: 'Format',
        icon: '#️⃣',
    },
    {
        id: 'abVariants',
        type: 'toggle',
        label: { es: 'Generar Variantes A/B', en: 'Generate A/B Variants' },
        defaultValue: false,
        section: 'Format',
        icon: '🔀',
    },
    {
        id: 'includeVisualBrief',
        type: 'toggle',
        label: { es: 'Incluir Brief Visual (imagen/video)', en: 'Include Visual Brief (image/video)' },
        defaultValue: true,
        section: 'Format',
        icon: '🎨',
    },
    {
        id: 'seriesMode',
        type: 'toggle',
        label: { es: 'Modo Serie (1/5, 2/5, etc.)', en: 'Series Mode (1/5, 2/5, etc.)' },
        defaultValue: false,
        section: 'Format',
        icon: '📚',
    },
    {
        id: 'culturalContext',
        type: 'select',
        label: { es: 'Contexto Cultural', en: 'Cultural Context' },
        defaultValue: 'us',
        options: [
            { value: 'us', label: { es: 'US / Canada', en: 'US / Canada' } },
            { value: 'europe', label: { es: 'Western Europe', en: 'Western Europe' } },
            { value: 'latam', label: { es: 'Latin America', en: 'Latin America' } },
            { value: 'east_asia', label: { es: 'East Asia', en: 'East Asia' } },
            { value: 'nordics', label: { es: 'Nordics', en: 'Nordics' } },
            { value: 'middle_east', label: { es: 'Middle East', en: 'Middle East' } },
        ],
        section: 'Psychology',
        icon: '🌍',
    },
    {
        id: 'visualStyle',
        type: 'select',
        label: { es: 'Estilo Visual', en: 'Visual Style' },
        defaultValue: 'photo',
        options: [
            { value: 'photo', label: { es: 'Foto Producto High-End', en: 'High-End Product Photo' } },
            { value: 'cine', label: { es: 'Cinemático', en: 'Cinematic' } },
            { value: '3d', label: { es: '3D Abstracto / Octane', en: '3D Abstract / Octane' } },
            { value: 'cyber', label: { es: 'Cyberpunk / Neon', en: 'Cyberpunk / Neon' } },
            { value: 'min', label: { es: 'Minimalista / Bauhaus', en: 'Minimalist / Bauhaus' } },
            { value: 'glitch', label: { es: 'Glitch Art', en: 'Glitch Art' } },
        ],
        section: 'Format',
        icon: '🎨',
    },
    {
        id: 'visualElements',
        type: 'text',
        label: { es: 'Elementos Visuales Clave', en: 'Key Visual Elements' },
        placeholder: { es: 'Ej: Neon lights, Smoke, Cyber skull...', en: 'Ex: Neon lights, Smoke, Cyber skull...' },
        section: 'Format',
        icon: '🖼️',
    },
];
